{% set name = "tinyobjloader" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b9d08b675ba54b9cb00ffc99eaba7616d0f7e6f6b8947a7e118474e97d942129

build:
  number: 0
  script:
    - mkdir $PREFIX/include                                # [unix]
    - cp $SRC_DIR/tiny_obj_loader.h $PREFIX/include        # [unix]
    - mkdir $PREFIX\include                                # [win]
    - xcopy /S %SRC_DIR%\tiny_obj_loader.h %LIBRARY_INC%   # [win]

test:
  commands:
    - test -f ${PREFIX}/include/tiny_obj_loader.h          # [unix]
    - if not exist %LIBRARY_INC%\tiny_obj_loader.h exit 1  # [win]

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tiny but powerful single file wavefront obj loader written in C++03.
  description: |
    Tiny but powerful single file wavefront obj loader written in C++03.
    No dependency except for C++ STL.
    It can parse over 10M polygons with moderate memory and time.
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - traversaro
    - benjaminrwilson
